name: Deploy to Uat-Prod
# Run the workflow whenever change is pushed into the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Optional: environment variables can be injected here
# You can add these variables in your repository Settings - Secrets and variables - Actions - variables
# env:

# There are two jobs in this workflow - build and deploy
jobs:
  # Builds the application for production.
  # You should configure this environment as close as possible to the production environment, e.g. using Ubuntu for Linux apps, using the same Node version
  fail-if-manual-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check if workflow is manually triggered for any other branch which is not main
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref_name }}" != "main" ]]; then
            echo "Manual trigger on any other branch is not allowed."
            exit 1
          else
            echo "Workflow is running as expected."
          fi

  build:
    runs-on: ubuntu-latest
    needs: fail-if-manual-main
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
        # Other scripts if configured should be added here, such as linting, formating

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: dist # This should be your distribution path, not the root path

  # Deploy the application to Azure
  deploy-uat:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "UAT"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - name: "Deploy to Azure Web App(uat)"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-pipeline-uat
          # slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_UAT_PUBLISHPROFILE }} # Publish profile should always be stored as secrets in your repository Settings - Secrets and variables - Actions - secrets
          package: .

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-uat
    environment:
      name: "PROD"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      - name: "Deploy to Azure Web App(prod)"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: test-pipeline-prod
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PROD_PUBLISHPROFILE }} # Publish profile should always be stored as secrets in your repository Settings - Secrets and variables - Actions - secrets
          package: .
